apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rjdpm4gbw-nodejs 
  janus-idp.io/tekton: rjdpm4gbw-nodejs
  backstage.io/kubernetes-id: rjdpm4gbw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rjdpm4gbw-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  