apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rjdpm4gbw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rjdpm4gbw-nodejs 
  name: rjdpm4gbw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rjdpm4gbw-nodejs 
